version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/app

    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      # Other build steps here...

      # Authenticate with AWS ECR using CircleCI secrets dsgsdg
      # Authenticate with AWS ECR using CircleCI secrets dsgsdg
      - run:
          name: Authenticate with AWS ECR
          command: aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_REGISTRY_URL

      # Other steps...

workflows:
  version: 2
  build:
    jobs:
      - build
