version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/app

    steps:
      - checkout
      - setup-docker-engine
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
        # Other build steps here... asfasf

      # Authenticate with AWS ECR using CircleCI secrets dsgsdg
      # Authenticate with AWS ECR using CircleCI secrets dsgsdg asfasf
      - run:
          name: Authenticate with AWS ECR
          command: aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_REGISTRY_URL
      - run:
          name: Create repo
          command : aws erc create-repository --repository-name myapp
      # Other steps...
      - run:
          name: Build and Tag Docker Image
          command: |
            docker build -t myapp:latest .
            docker tag myapp:latest $AWS_REGISTRY_URL/myapp:latest

      - run:
          name: Push Docker Image to AWS ECR
          command: docker push $AWS_REGISTRY_URL/myapp:latest

workflows:
  version: 2
  build:
    jobs:
      - build
