version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/app

    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Install Docker
          command: |
            sudo curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            
      - run:
          name: Start Docker Service
          command: sudo service docker start


      # Other build steps here...

      # Authenticate with AWS ECR using CircleCI secrets dsgsdg
      # Authenticate with AWS ECR using CircleCI secrets dsgsdg
      - run:
          name: Authenticate with AWS ECR
          command: aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_REGISTRY_URL

      # Other steps...
      - run:
          name: Build and tage docker image
          command: | 
            docker-compose build 
            docker tag my-image-placeholder:latest $AWS_REGISTRY_URL/my-app:my-tag


      - run:
          name: Push to AWS ERC
          command: | 
            docker push $AWS_REGISTRY_URL/my-app:my-tag

workflows:
  version: 2
  build:
    jobs:
      - build
