- name: Copy deployment configuration test
  copy:
    src: "{{ ENVIRONMENT_NAME }}-project-deployment.yaml"
    dest: $HOME

- name: Apply deployment configuration
  shell: "./bin/kubectl/ apply -f {{ ENVIRONMENT_NAME }}-project-deployment.yaml"
  args:
    chdir: $HOME
