- name: Copy deployment configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-project-deployment.yaml"
    dest: $HOME

- name: Apply deployment configuration
  shell: "kubectl apply -f {{ ENVIRONMENT_NAME }}-project-deployment.yaml"
  args:
    chdir: $HOME
