#- name: Copy deployment configuration test
#  copy:
#    src: "{{ ENVIRONMENT_NAME }}-project-deployment.yaml"
#    dest: $HOME
#
#- name: Apply deployment configuration test test
#  shell: "./bin/kubectl apply -f {{ ENVIRONMENT_NAME }}-project-deployment.yaml"
#  args:
#    chdir: $HOME

- name: "Copy deployment configuration to $HOME"
  gather_facts: false
  become: yes
  tasks:
    - name: Create directory if it doesn't exist
      file:
        path: "{{ lookup('env', 'HOME') }}"
        state: directory
        recurse: yes
        owner: ubuntu
        group: ubuntu

    - name: Copy deployment configuration to $HOME
      copy:
        src: "{{ ENVIRONMENT_NAME }}-project-deployment.yaml"
        dest: "{{ lookup('env', 'HOME') }}/{{ ENVIRONMENT_NAME }}-project-deployment.yaml"

- name: "Apply deployment configuration using kubectl"
  gather_facts: false
  become: yes
  tasks:
    - name: Set the KUBECONFIG environment variable
      shell: "export KUBECONFIG=~/.kube/config"
      become_user: ubuntu  # Set the environment variable for the user

    - name: Apply deployment configuration using kubectl
      shell: "./bin/kubectl apply -f {{ ENVIRONMENT_NAME }}-project-deployment.yaml"
      args:
        chdir: "{{ lookup('env', 'HOME') }}"
