---
- name: "Download kubectl"
  shell: curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  args:
    chdir: $HOME

- name: "Apply execute permissions to the binary"
  shell: chmod +x ./kubectl
  args:
    chdir: $HOME

- name: "Move the binary to /usr/local/bin"
  become: yes
  shell: sudo mv ./kubectl /usr/local/bin/kubectl

- name: "Add the $HOME/bin path to the shell initialization file test"
  shell: echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
  args:
    chdir: $HOME
