---
- name: "Download kubectl"
  shell: curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
  args:
    chdir: $HOME

- name: "Apply execute permissions to the binary"
  shell: chmod +x ./kubectl
  args:
    chdir: $HOME

- name: "Move the binary to /usr/local/bin"
  become: yes
  shell: sudo mv ./kubectl /usr/local/bin/kubectl

- name: "Add the $HOME/bin path to the shell initialization file"
  shell: echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
  args:
    chdir: $HOME
