---
- name: "Download kubectl"
  hosts: management
  user: ubuntu
  gather_facts: false
  become: yes
  tasks:
    - name: Download kubectl binary
      shell: curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
      args:
        chdir: $HOME
      environment:
        HOME: "/home/ubuntu"  # Update with the correct home directory if necessary

    - name: Apply execute permissions to the binary
      shell: chmod +x kubectl
      args:
        chdir: $HOME

    - name: Move the binary to /usr/local/bin
      shell: sudo mv kubectl /usr/local/bin/
