---
- hosts: localhost
  tasks:
    - name: Download The AWS CLI Archive
      shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      args:
        chdir: $HOME

    - name: Unzip the AWS CLI Archive
      become: yes
      shell: unzip -o awscliv2.zip
      args:
        chdir: $HOME

    - name: Install the AWS CLI
      become: yes  # Enable privilege escalation
      shell: ./aws/install
      args:
        chdir: $HOME
