- name: Copy service configuration
  copy:
    src: "{{ ENVIRONMENT_NAME }}-project-service.yaml"
    dest: $HOME

- name: Create service configuration
  command: "$HOME/bin/kubectl apply -f {{ ENVIRONMENT_NAME }}-project-service.yaml"
  args:
    chdir: $HOME
